@startuml
class SpArray{
    datas : SpLink[]
}

class SpTable{
   datas : SpLink[]
}


class SpLink{
  tag   : SpString
  value : SpValue
}
SpTable *--> SpLink
SpLink  *--> SpNumber
SpLink  *--> SpString
SpLink  *--> SpValue

Root  --> TableA
TableA --> TableB
TableA --> DataSet1
TableB --> DataSet2
TableB --> TableB
TableB --> DataSet1
@enduml